spring:
 application:
   name: grupo-22-oo2-2024
 datasource:
   password: ${DB_PASSWORD}
   url: ${DB_URL}
   username: ${USERNAME}
   driverClassName: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.MySQLDialect
    